utils::globalVariables(
  c(
    "all_locales",
    "all_currency_codes",
    "default_locales",
    "locale_names",
    "dates",
    "dates_generic",
    "numbers",
    "currencies",
    "characters",
    "character_labels",
    "delimiters",
    "layout",
    "script_metadata",
    "units",
    "tz_names",
    "tz_formats"
  )
)
